### ISSUE TITLE
Field edit links not clickable when Repeater field set to "Items always open"

### ISSUE THREAD

**Issue by Toutouwai** [rolandtoth/AdminOnSteroids#101]
For some reason when a Repeater field has the setting "Items always open", it isn't possible to click the field edit link for that field. The field open/close toggle seems to steal the click - in the screen capture below you can see the toggle icon flash although it doesn't actually toggle the field open/closed.

![aos-issue](https://user-images.githubusercontent.com/1538852/47612091-4fb73d00-dad8-11e8-87cd-9bfab20d4fe4.gif)

**Comment by rolandtoth** [comment]
Thanks, I was expecting markup differences but in fact it was another thing. AOS checks whether the edit link is already in the field's markup (see #96). Because repeaters include other fields their markup already contain edit links, so the edit link is not added. Now I excluded repeaters from this so it should work as expected.

**Comment by Toutouwai** [comment]
Thanks for the speedy fix.
