### ISSUE TITLE
Can't expand page actions on /processwire/page/lister/

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#33]
When I visit /processwire/page/lister/, it will list the pages on my site.  When click on the right arrow nothing happens.  No errors in the console.

![find processwire pwtwig dev 2017-01-08 14-16-10](https://cloud.githubusercontent.com/assets/40570/21753196/27c394ce-d5ad-11e6-9d97-a57600017f94.jpg)

If disable AOS temporarily via the link, everything starts working again.

Lister tweaks is disabled.  Page List tweaks is disabled.

**Comment by rolandtoth** [comment]
I can reproduce, thanks. Until the fix just click on the page name and then the arrow will be functional.

The issue is that ListerTweaks submodule's "Show action buttons on hover" tweak was ignoring the submodule ON/OFF state.
(technically this tweak is part of the "ListerTweaks_options" submodule)

**Comment by rolandtoth** [comment]
Please check if it's working for you in v118.

**Comment by gmclelland** [comment]
Thank you, it is working now but the page action hover styling is black text when I think it should be white text.

**Comment by gmclelland** [comment]
Ahh.. I see the other commits after 1.1.8

**Comment by rolandtoth** [comment]
Yes there are a few but only the last one fixes the black text on hover (added only a minute ago).
