### ISSUE TITLE
UiKit sticky header problem on login screen

### ISSUE THREAD

**Issue by adrianbj** [rolandtoth/AdminOnSteroids#77]
The header is pushed down what looks to be the height of the header itself leaving a weird whitespace above the header.

**Comment by rolandtoth** [comment]
Thanks, I've fixed it in v1.6.6, though the issue was not really came from aos but PW. On the login page the mobile header is used and the desktop one is made hidden. 

I've disabled the fixed header here entirely because it's unlikely that the page will be higher than the window. There are also adjustments to the compact header and the centered login form too.

**Comment by adrianbj** [comment]
Thank you!
