### ISSUE TITLE
Strange errors in console

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#8]
Hi tpr,

I just upgraded to the latest AOS module on PW3.0.33.  When I'm looking at the page tree on /admin/page/, I'm seeing these errors in the console.  It keeps growing bigger:

Why is it referencing this domain: http://mosolygo.paqartdesign.com/admin/module/edit?name=AdminOnSteroids&getTemplateEditLink=search ?

![consoleerrors](https://cloud.githubusercontent.com/assets/40570/18811798/5553d5fc-8283-11e6-84e4-60224c1e0bbd.jpg)

**Comment by rolandtoth** [comment]
Sorry, I forgot to replace the url of an ajax call. Check v069, it should be fixed now (tested on another domain too).

The error came from the FieldAndTemplateEditLink submodule which was extended to include the main pagelist items too. Here I needed to use another approach that's why the ajax calls. They are executed once for a pagelist item so they won't grow infinitely.

**Comment by gmclelland** [comment]
Thank you for the fixes.
