### ISSUE TITLE
New 'Move' function in Page Tree

### ISSUE THREAD

**Issue by gmclelland** [rolandtoth/AdminOnSteroids#9]
Hi tpr,

Just wanted to let you know that I tried the new move functionality in the page tree, but I seem to be having trouble moving a page directly under Home.

Do you experience this?

![screencast 2016-09-27 15-16-48](https://cloud.githubusercontent.com/assets/40570/18890308/2fb181b0-84c6-11e6-8edb-c96d3ad0bf36.gif)

Also to get it to work I had to download the file from https://processwire.com/talk/applications/core/interface/file/attachment.php?id=8731 and rename it from ProcessPageList.js to ProcessPageList.min.js before it would start working.  You may want to include that in your instructions in the forum or on the module's readme.txt if you want more testers.

Hope that helps

**Comment by rolandtoth** [comment]
Thanks for your remarks!

The pagelist move updates are not part of AOS (and never be), I just shared it in that forum topic because it was requested there.

I have made improvements to it and it's more usable now though I still need to check a few things. I will also decouple its CSS from AOS and create a pull request in PW's repo.

**Comment by gmclelland** [comment]
Good to hear.  I can do some more testing when your're ready to share the improvements you've made.

I'll go ahead and close this issue since it's not related to AOS.
